version: '3.8'

services:

  web:
    container_name: web
    build:
      context: .
      target: php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 9000:8080
    depends_on:
      - mysql-db
      - cache-db
    networks:
      - qlope-network
    logging:
      driver: journald
      options:
        tag: mytag

  # Mysql database service container configration
  mysql-db:
    container_name: mysql-db
    image: mysql:8.2
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "dev"
      MYSQL_PASSWORD: "FhgVoFuOrWspc3TgBIA2K4dZGuJTPwSYBoLnNckcaxy"
      MYSQL_DATABASE: "qlope"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
      - qlope-network

  # Cache database service container configration
  cache-db:
    container_name: cache-db
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    ports:
      - "6379:6379"
    volumes:
      - "cache-data:/data"
    networks:
      - qlope-network
volumes:
  db-data:
    driver: local
  cache-data:
    driver: local
networks:
  qlope-network:
    driver: bridge